Experiment: usvisa_experiment
Model_name: Random_Forest_Regression
Parameters:
  max_depth: 15
  min_samples_leaf: 1
  min_samples_split: 2
  n_estimators: 250
R2_score: RandomForestClassifier(max_depth=15, n_estimators=250, random_state=42)
Run_name: null
